### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by bellanz80** [IGNF/NeatMap#4]
Hi,
I have an error trying to install the plug. I have tried from the QGIS repository, how to download the ZIP from Github.
Annex screenshot

QGIS: 3.4.2
WINDOWS: 10 64 bit, 1809 - 17763.194
Thank you
Luca
![error](https://user-images.githubusercontent.com/38449926/50164287-dfdb5c80-02a7-11e9-8f01-2aaa8686b52b.PNG)

**Comment by mbrasebin** [comment]
Hello,

thank you for the feedback, it seems to be related to this error : https://stackoverflow.com/a/50764560

I have pushed the proposed solution : d55f6bcc3d4ba06f18894824e5ec5b6ce379635e  and tested on a computer where the bug seems to be the same.

Can you try the plugin from the Github repository ?

Mickaël

**Comment by julienperret** [comment]
Please try version 1.1 and create and reopen the issue if the problem persists.

**Comment by mbrasebin** [comment]
New patch for windows, does it work for you ?

dd2a97fc5d063a28d63b43007b7fea76892affd4

**Comment by bellanz80** [comment]
Hi. unfortunately I can not install it, the error keeps appearing.
Neatmap version 1.1
QGIS 3.4.2
windows 10 64 bit 1809
Thank you very much for all the support.

![neat_map](https://user-images.githubusercontent.com/38449926/50852722-f411f700-1345-11e9-9e13-7b2c279d0f20.PNG)

**Comment by bellanz80** [comment]
Hi. I have performed the two operations, the first in windows, returns an error, as if it did not locate python.
the second in QGIS does not give any error. Thanks for the support.

![2](https://user-images.githubusercontent.com/38449926/51047691-c10e7400-158e-11e9-9cf8-3af731fb5a61.PNG)
![1](https://user-images.githubusercontent.com/38449926/51047692-c1a70a80-158e-11e9-9323-4cb821c4979f.PNG)

**Comment by mbrasebin** [comment]
Hello,

it was quite hard to correct the bug, but I think that we have found a solution.

We have uploaded a new version of the plugin (1.2) that should correct that. So, you have, from QGIS plugin manager, to : 
1 - Uninstall the current version of the plugin,
2 - Install the new version.

Tell us if it works,

Best regards,

Mickaël

**Comment by bellanz80** [comment]
Yes! everything works perfectly! Now calmly I will test it thoroughly, thank you very much for your constant support.
Luca

**Comment by mbrasebin** [comment]
Thank you for being our Windows user and do not hesitate to share if you produce some nice results with the plugin

Mickaël

**Comment by bhoudusse** [comment]
Hello,

i'm a French user and I have a similar problem on my professional PC (Win 7, Qgis 3.6.0, Python 3.7.0)

In my case, it seems to be a problem with the installation of pip ; i tried to reinstall the lib with the Qgis' advanced installer, but the problem message still occurs : see captured message at the end

I tried to do the quick tests you propose:
- in the osgeo shell, the command python3 -V returns : Python 3.7.0
- in the qgis console, the command import pip returns an error : 

> Traceback (most recent call last):
  File "C:\OSGEO4\~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pip'

I'd really like to help, because I'd like to test the plugin against some of my data (I'm an archeologist and I'm really interested in testing morphological indicators.


Bertrand

Captured error message at Qgis launch : 

Impossible de charger l'extension 'NeatMap' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'pip' 
Traceback (most recent call last):
              File "C:/Users/bhoudusse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NeatMap\classification.py", line 9, in 
              from pip._internal import main
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'pip'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/Users/bhoudusse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NeatMap\__init__.py", line 34, in classFactory
              from .neatmap import NeatMap
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/bhoudusse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NeatMap\neatmap.py", line 38, in 
              from .classification import *
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/bhoudusse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NeatMap\classification.py", line 16, in 
              from pip._internal import main
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'pip'
